version: '2'

services:
  gradle:
    image: gradle:jre-alpine
    working_dir: /usr/src/app
    volumes:
    - ".:/usr/src/app"
    network_mode: bridge
    entrypoint: /usr/bin/gradle --gradle-user-home .gradle --info --build-cache

  groovy:
    image: groovy:alpine
    working_dir: /usr/src/app
    volumes:
    - ".:/usr/src/app"
    network_mode: bridge
    entrypoint: groovy -classpath src/:vars/:test/

  groovyc:
    image: groovy:alpine
    working_dir: /usr/src/app
    volumes:
    - ".:/usr/src/app"
    network_mode: bridge
    entrypoint: groovyc -classpath src/:vars/
